/**
 * **389. Find the Difference**
 * 
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 * Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

 * @param {string} s
 * @param {string} t
 * @return {character}
 */
const findTheDifference = function (s, t) {
    let result = 0;

    // XOR all characters in string s
    for (let i = 0; i < s.length; i++) {
        result ^= s.charCodeAt(i);
    }

    // XOR all characters in string t
    for (let i = 0; i < t.length; i++) {
        result ^= t.charCodeAt(i);
    }

    // Convert the result back to a character and return
    return String.fromCharCode(result);
};

const s = 'abcd',
    t = 'abcde';
// Output: "e"
// Explanation: 'e' is the letter that was added.
console.log(findTheDifference(s, t));

const s1 = '',
    t1 = 'y';
// Output: "y"
console.log(findTheDifference(s1, t1));
